namespace AussieLink.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddMelbourneSuburb : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Abbotsford')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Aberfeldie')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Airport West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Albanvale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Albert Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Albion')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Alphington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Altona')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Altona East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Altona Meadows')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Ardeer')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Armadale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Arthurs Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Ascot Vale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Ashburton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Aspendale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Attwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Auburn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Auburn South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Avondale Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Avonsleigh')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Badger Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Balaclava')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Balwyn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Balwyn North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bangholme')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Banyule')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Batman')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bayswater')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Beaconsfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Beaconsfield Upper')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Beaumaris')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bedford Road')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Beenak')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Belgrave')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bellfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bend Of Islands')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bentleigh')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bentleigh East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Berwick')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Beveridge')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Blackburn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Blind Bight')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bonbeach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Boronia')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Botanic Ridge')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Box Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Box Hill North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brandon Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Braybrook')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brentford Square')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Briar Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brighton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brighton East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brighton Road')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Broadmeadows')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brookfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brooklyn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brunswick')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brunswick East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Brunswick South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bulla')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bulleen')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bundoora')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Bunyip')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Burnley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Burnside')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Burwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Burwood East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Calder Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Camberwell')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Camberwell East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Campbellfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Cardinia')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Carlton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Carlton North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Carnegie')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Carrum')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Caulfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Caulfield East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Caulfield Junction')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Chadstone')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Cheltenham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Chirnside Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Christmas Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Clarinda')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Clayton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Clifton Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Cockatoo')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Cocoroc')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Coldstream')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Coolaroo')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Cora Lynn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Cotham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Craigieburn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Croydon')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Diamond Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Diggers Rest')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Dingley Village')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Docklands')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Doncaster')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Doncaster East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Donvale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Doreen')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Doveton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'East Melbourne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Eden Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Elsternwick')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Eltham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Endeavour Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Epping')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Essendon Fields')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Fawkner')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Ferntree Gully')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Ferny Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Fitzroy')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Flemington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Footscray')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Fountain Gate')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Garden City')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Gembrook')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Gilberton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Gilderoy')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Gladstone Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Glenroy')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Greenvale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Hallam')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Hampton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Hampton Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Hawksburn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Heatherton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Heathwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Highett')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Hoppers Crossing')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Hotham Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Hughesdale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Ivanhoe')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Kallista')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Kalorama')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Keilor')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Keilor Downs')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Keilor East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Kew East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Keysborough')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Kilsyth')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Kinglake')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Knox City Centre')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Knoxfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Kooyong')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Kurunjang')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Lalor')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Laverton North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Lilydale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Little River')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Lower Plenty')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Lynbrook')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Macleod')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mambourin')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Maryknoll')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Melbourne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Melbourne Airport')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Melbourne University')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mentone')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Menzies Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mill Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mitcham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Monash University')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Monbulk')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mont Albert')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Montmorency')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Montrose')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Moonee Ponds')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Moorabbin')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mooroolbark')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mount Dandenong')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mount Evelyn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mount Waverley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Mulgrave')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Narre Warren')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Newport')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Noble Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'North Warrandyte')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Northcote')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Oaklands Junction')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Oakleigh South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Officer')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Olinda')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Pakenham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Panton Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Park Orchards')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Pascoe Vale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Plenty')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Plumpton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Prahran')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Reservoir')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Rowville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Sandown Village')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Sandringham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Sassafras')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Scoresby')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Sherbrooke')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Silvan')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Smiths Gully')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Somerton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'South Melbourne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'South Morang')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'South Wharf')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'South Yarra')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'St Andrews')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'St Kilda')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Sunbury')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Templestowe')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Templestowe Lower')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'The Basin')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'The Patch')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Thomastown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Thornbury')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Tremont')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Tynong')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'University Of Melbourne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Upwey')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Vermont')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Wattle Glen')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'West Melbourne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Williams Landing')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Williamstown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Wollert')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Wonga Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Woodstock')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Yan Yean')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Yarrambat')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (2, 'Yarraville')");
        }
        
        public override void Down()
        {
        }
    }
}
