namespace AussieLink.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateSydneySuburbs : DbMigration
    {
        public override void Up()
        {
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Abbortsford Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Abbotsbury')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Abbotsford')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Acacia Gardens')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Agnes Banks')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Airds')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Akuna Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Alexandria')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Alfords Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Allambie')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Allambie Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Allawah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ambarvale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Annandale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Annangrove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Anzac Village')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Appin')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Arcadia')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Arncliffe')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Arndell Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Artarmon')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ashbury')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ashcroft')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ashfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Asquith')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Auburn North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Auburn South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Auburn West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Auburn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Audley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Austral')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Avalon')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Avalon Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Badgerys Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bald Face')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Balgowlah Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Balgowlah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Balls Head')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Balmain East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Balmain')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Balmoral Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Balmoral Village')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Balmoral')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bangor')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Banksia')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Banksmeadow')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bankstown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bankstown Airport')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bankstown East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bankstown North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bantry Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Barden Ridge')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bardwell Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bardwell Valley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bargo')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bass Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Baulkham Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bayview')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Beacon Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Beaconsfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Beauty Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Beecroft')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Belfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Belimba Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bella Vista')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bellevue Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Belmore')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Belrose')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ben Buckler')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Berala')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Berkshire Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Berowra')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Berowra Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Berowra Waters')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Berrilee')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Berrys Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Beverley Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Beverly Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Beverly Hills North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bexley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bexley North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bexley South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bexley West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bickley Vale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bidwill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bilgola')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bilgola Plateau')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Birchgrove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Birkenhead Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Birrong')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Blacktown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Blair Athol')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Blairmount')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Blakehurst')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Blaxcell')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Blaxland')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Blaxlands Ridge')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Blues Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bobbin Head')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bondi')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bondi Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bondi Junction')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bonnet Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bonnyrigg')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bonnyrigg Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Boronia Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bossley Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Botany')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bowen Mountain')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bradbury')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bradleys Head')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Breakfast Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Brickfield Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Brighton-Le-Sands')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bringelly')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Broadway')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bronte')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Brooklyn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Brookvale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Brownlow Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bundeena')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Bungan Head')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Burraneer')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Burwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Burwood Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Busby')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cabarita')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cabarita Junction')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cabramatta')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cabramatta Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cabramatta West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cabravale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cambridge Gardens')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cambridge Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Camden')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Camden South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Camellia')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cammeray')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Campbelltown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Campbelltown North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Camperdown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Campsie')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Canada Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Canley Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Canley Vale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Canoelands')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Canterbury')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Caravan Head')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Careel Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Caringbah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Carlingford')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Carlingford Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Carlingford North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Carlton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Carnes Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Carramar')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Carss Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cartwright')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Castle Cove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Castle Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Castlecrag')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Castlereagh')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Casula')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Catherine Field')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cattai')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cawdor')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cecil Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cecil Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Centennial Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Central')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Central Macdonald')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Charing Cross')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chatswood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chatswood West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chatsworth')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cheltenham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cherrybrook')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chester Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chifley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chinatown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chippendale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chipping Norton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chiswick')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chowder Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Chullora')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Church Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Circular Quay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Claremont Meadows')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Clarendon')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Clareville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Claymore')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Clemton Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Clifton Gardens')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Clontarf')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Clovelly')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Clovelly West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Clyde')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Coasters Retreat')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cobbitty')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cockatoo Island')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cogra Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Colebee')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Collaroy')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Collaroy Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Collaroy Plateau')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Colyton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Comleroy Road')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Como')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Como West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Concord')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Concord East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Concord North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Concord South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Concord West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Condell Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Connells Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Coogee')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Coogee North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cornwallis')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cottage Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Couridjah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cowan')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cranebrook')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cremorne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cremorne Junction')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cremorne Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cromer')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cromer Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Cronulla')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Crows Nest')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Croydon')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Croydon Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Curl Curl')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Currans Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Currawong Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Daceyville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dangar Island')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Darling Harbour')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Darling Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Darlinghurst')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Darlington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Davidson')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dawes Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dean Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dee Why')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dee Why Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Denham Court')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Denistone')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Denistone East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Denistone West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dharruk')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Diamond Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dobroyd Head')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dobroyd Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dolans Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dolls Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Doonside')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Double Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Douglas Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dover Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Drummoyne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Duffys Forest')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dulwich Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dundas')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dundas Valley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dunheved')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Dural')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Eagle Vale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Earlwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'East Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'East Killara')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'East Kurajong')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Eastlakes')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'East Lindfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'East Roseville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'East Ryde')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'East Sydney')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Eastern Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Eastgardens')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Eastwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ebenezer')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Edensor Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Edgecliff')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Edmondson Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Elanora Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Elderslie')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Elizabeth Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ellis Lane')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Elvina Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Emerton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Emu Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Emu Plains')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Enfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Enfield South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Engadine')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Engalorie Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Enmore')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Epping')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Epping West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ermington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Erskine Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Erskineville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Erskineville South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Eschol Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Eskdale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Eveleigh')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Fairfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Fairfield East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Fairfield Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Fairfield West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Fairlight')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Faulconbridge')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Fiddletown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Five Dock')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Flemington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Forest Glen')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Forest Lodge')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Forestville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Fox Valley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Freemans Reach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Frenchs Forest')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Frenchs Forest East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Fullers Bridge')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Galston')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Garden Island')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Georges Hall')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Georges Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Gilead')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Girraween')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Gladesville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glebe')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glebe Island')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glebe Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glen Alpine')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glenbrook')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glendenning')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glenfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glenhaven')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glenmore')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glenmore Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glenorie')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glenwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Glossodia')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Goat Island')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Golden Grove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Gordon')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Gore Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Graham Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Granville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Grasmere')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Grays Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Great Mackerel Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Green Valley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Greenacre')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Greendale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Greenfield Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Greenwich')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Greenwich Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Greystanes')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Grose Vale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Grose Wold')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Guildford')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Guildford North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Guildford West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Gunderman')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Gunnamatta Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Gymea')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Gymea Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Haberfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hammondville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Harbord')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Harbord West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Harrington Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Harris Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hassall Grove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hawkesbury Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Haymarket')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Heathcote')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hebersham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Heckenberg')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Henley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hewitt')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hillsdale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hillside')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hinchinbrook')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'HMAS Penguin')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hobartville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Holroyd')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Holsworthy')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Holsworthy Barracks')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Homebush')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Homebush Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Homebush West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Horningsea Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hornsby')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hornsby Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Horsley Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hoxton Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hunters Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Huntingwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Huntleys Cove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Huntleys Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hurlstone Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hurstville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Hurstville Grove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Illawong')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ingleburn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ingleburn Military Camp')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ingleburn Village')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ingleside')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Jamisontown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Jannali')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Jannali West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kangaroo Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kareela')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kearns')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kellyville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kellyville Ridge')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kemps Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kenny Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kensington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kenthurst')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kentlyn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Killara')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Killarney Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kings Cross')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kings Langley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kings Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kingsway')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kingsgrove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kingswood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kingswood Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kirkham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kirrawee')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kirribilli')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kissing Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kogarah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kogarah Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ku-ring-gai Chase National Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'urmond')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kurnell')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kurraba Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kurrajong')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kurrajong Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kurrajong Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kyeemagh')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Kyle Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'La Perouse')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lake Parramatta')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lakemba')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lakesland')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lalor Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Landsvale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lane Cove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lane Cove North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lane Cove West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lansdowne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lansvale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lapstone')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lavender Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lawson')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Leichhardt')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Leightonfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lemon Grove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Leonay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Leppington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lethbridge Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Leumeah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lewisham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Liberty Grove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lidcombe')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lilli Pilli')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lilyfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lindfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Linley Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Linns Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Little Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Liverpool')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Liverpool North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Liverpool South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Liverpool West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Loftus')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lovett Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lucas Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lugarno')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Lurnea')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Macdonaldtown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Macquarie Fields')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Macquarie Links')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Macquarie Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Macquarie University')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Maianbar')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Malabar')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Manly')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Manly East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Manly Vale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Maraylya')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Marayong')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Maroota')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Maroubra')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Maroubra Junction')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Maroubra South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Marrickville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Marrickville West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Marrickville South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Marsden Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Marsfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mascot')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Matraville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mays Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'McCallums Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'McGraths Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'McMahons Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Meadowbank')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Melrose Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Melville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Menai')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Menangle')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Menangle Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Merrylands')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Merrylands West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Middle Cove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Middle Dural')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Middle Head')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Miller')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Millers Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Milperra')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Milsons Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Minchin Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Minchinbury')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Minto')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Minto Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Miranda')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Model Farms')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mona Vale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Monterey')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mooney Mooney')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Moore Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Moorebank')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Morning Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mortdale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mortlake')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mosman')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Annan')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Colah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Druitt')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Hunter')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Kuring-Gai')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Lewis')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Pleasant')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Pritchard')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Riverview')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Tomah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Vernon')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Victoria')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Wilga')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount Wilson')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mount York')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mountain Lagoon')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mowbray Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mulgoa')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Mulgrave')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Narellan')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Narellan Vale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Naremburn')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Narrabeen')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Narraweena')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Narwee')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Nelson')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Neutral Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Neutral Bay Junction')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Newington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Newport')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Newport Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Newtown')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Nielsen Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Normanhurst')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Balgowlah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Bondi')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Curl Curl')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Epping')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Head')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Manly')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Ryde')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Steyne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Strathfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Sydney')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'North Turramurra')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Northbridge')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Northwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Oakdale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Oakhurst')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Oakville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Oatlands')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Oatley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Old Guildford')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Old Toongabbie')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Oran Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Orange Grove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Orangeville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Orchard Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Osborne Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Oxford Falls')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Oxley Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Oyster Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Paddington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Padstow')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Padstow Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Pagewood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Palm Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Panania')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Parklea')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Parramatta')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Parramatta East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Peakhurst')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Peakhurst Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Peakhurst South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Pendle Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Pennant Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Penrith')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Penshurst')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Petersham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Phillip Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Picnic Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Picton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Pitt Town')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Pitt Town Bottoms')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Pleasure Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Plumpton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Point Piper')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Port Botany')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Portland')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Prestons')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Prospect')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Punchbowl')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Putney')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Pymble')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Pyrmont')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Quakers Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Queens Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Queenscliff')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Raby')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ramsgate')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ramsgate Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Randwick')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Redfern')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Regents Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Regentville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Revesby')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Revesby Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Revesby North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rhodes')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Richmond')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Richmond Lowlands')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Riverstone')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Riverview')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Riverwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rockdale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rodd Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rogans Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rookwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rooty Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rose Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rose Bay North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rosebery')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rosehill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Roselands')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Roselea')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rosemeadow')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Roseville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Roseville Chase')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rossmore')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Round Corner')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rouse Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Royal National Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rozelle')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ruse')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rushcutters Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Russell Lea')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Rydalmere')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ryde')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sackville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sackville North')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sadleir')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sagar Place')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sandringham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sandy Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sans Souci')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Scheyville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Schofields')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Scotland Island')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Seaforth')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sefton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Seven Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Seven Hills West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Shalvey')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sherwood Grange')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Silverdale')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Silverwater')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Smeaton Grange')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Smithfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Smithfield West')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sorlie')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'South Granville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'South Head')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'South Hurstville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'South Maroota')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'South Penrith')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'South Steyne')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'South Turramurra')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'South Wentworthville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'South Windsor')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Spectacle Island')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Spit Junction')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Spring Farm')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Springwood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'St Albans')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'St Andrews')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'St Clair')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'St Leonards')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'St Marys')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'St Peters')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Stanhope Gardens')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Stanmore')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Strathfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Strathfield South')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Strawberry Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Summer Hill')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sun Valley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Surry Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sutherland')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sydenham')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sydney')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sydney Showground')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sydney Olympic Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sylvania')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sylvania Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Sylvania Waters')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Tahmoor')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Tamarama')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Tarban')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Taren Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Tempe')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Tennyson Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Terrey Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'The Basin')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'The Oaks')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'The Rocks')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'The Spit')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Theresa Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Thirlmere')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Thornleigh')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Tom Uglys Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Toongabbie')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Toongabbie East')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Tregear')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Tudera Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Tumbledown Dick')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Turramurra')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Turrella')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Ultimo')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Undercliffe')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'University Of N S W')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'University Of Sydney')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Valley Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Varroville')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Vaucluse')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Villawood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Vineyard')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Voyager Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wahroonga')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Waitara')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wakeley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wallacia')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wallgrove')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wareemba')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Warragamba')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Warrawee')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Warriewood')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Warriewood Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Warrimoo')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Warringah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Warumbul')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Warwick Farm')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Waterfall')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Waterloo')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Watsons Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Waverley')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Waverton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Werombi')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Werrington')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Werrington County')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Werrington Downs')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'West Hoxton')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'West Lindfield')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'West Pennant Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'West Pymble')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'West Ryde')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wetherill Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Whalan')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Whale Beach')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wheeler Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wheeny Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'White Bay')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wilberforce')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wiley Park')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Willmot')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Willoughby')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Windsor')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Windsor Downs')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wingala')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Winji Jimmi')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Winmalee')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Winston Hills')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wolli Creek')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wollstonecraft')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wondabine')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woodbine')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woodcroft')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woodford')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woollahra')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woollahra Point')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woolloomooloo')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woolooware')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woolwich')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woronora')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Woronora Heights')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Wynyard')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Yagoona')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Yanderra')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Yarramundi')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Yarrawarrah')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Yennora')");
            Sql("INSERT INTO dbo.Suburbs (PlaceId, Name) VALUES (1, 'Zetland')");

        }

        public override void Down()
        {
        }
    }
}
